namespace ManagerIV.Core;

/// <summary>
/// Interface encapsulating game version-specific behaviors, translations, and operations.
/// </summary>
public interface IBackendAdapter
{
    /// <summary>
    /// Detects the version profile of the game executable in the specified directory.
    /// </summary>
    GameVersionProfile DetectVersion(string gameDir);

    /// <summary>
    /// Resolves where a specific mod file should be deployed.
    /// </summary>
    DeployTarget ResolveTarget(ModFile file);

    /// <summary>
    /// Deploys a staged mod into the game directory with a given load order priority.
    /// </summary>
    Task DeployAsync(StagedMod mod, int priority);

    /// <summary>
    /// Removes a staged mod from the game directory.
    /// </summary>
    Task UndeployAsync(StagedMod mod);

    /// <summary>
    /// Reads the current load order from the physical layout.
    /// </summary>
    Task<LoadOrderModel> ReadLoadOrderAsync();

    /// <summary>
    /// Writes the given load order to the physical layout.
    /// </summary>
    Task WriteLoadOrderAsync(LoadOrderModel order);

    /// <summary>
    /// Returns the log file paths generated by backend tools (e.g. FusionFix, Ultimate ASI Loader).
    /// </summary>
    IEnumerable<string> BackendLogPaths();
}
